version: "3.8"

services:
  server:
    build: .
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - cache

  cache:
    image: redis:7.2.4
    restart: always
    ports:
      - 6379:6379
